### ISSUE TITLE
displayed fluxes not as indicated by constraints

### ISSUE THREAD

**Issue by hredestig** [DD-DeCaF/pathway-vis#14]
in harder dataset, the glucose import shown on map doesn't match the overlaid data

**Comment by hredestig** [comment]
![screen shot 2016-12-22 at 14 38 11](https://cloud.githubusercontent.com/assets/1300566/21427346/5c70c054-c854-11e6-8e37-f9ce04d41802.png)

**Comment by hredestig** [comment]
seems to be two different problems. Above, the backend isn't returning flux for GLCtex as above whereas it does return flux for GLCtex_copy1, which isn't used by the map so some map/model mismatch issue. The second problem is seen here:
![screen shot 2016-12-23 at 10 44 54](https://cloud.githubusercontent.com/assets/1300566/21451149/14068642-c8fd-11e6-8a6a-21eaffceffff.png)
where although ethanol flux should be set to 5 the model doesn't reflect this

**Comment by hredestig** [comment]
seems the issue is somewhere in the backend where `request.json()` is failing:

```
[web-1]2016-12-23T10:16:41.559021832Z Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8
[web-1]2016-12-23T10:16:41.571928212Z [2016-12-23 10:16:41 +0000] [13] [ERROR] Error handling request
[web-1]2016-12-23T10:16:41.571992729Z Traceback (most recent call last):
[web-1]2016-12-23T10:16:41.572007094Z   File "/usr/local/lib/python3.5/site-packages/aiohttp/server.py", line 265, in start
[web-1]2016-12-23T10:16:41.572017307Z     yield from self.handle_request(message, payload)
[web-1]2016-12-23T10:16:41.572025277Z   File "/usr/local/lib/python3.5/site-packages/aiohttp/web.py", line 96, in handle_request
[web-1]2016-12-23T10:16:41.572053567Z     resp = yield from handler(request)
[web-1]2016-12-23T10:16:41.572065917Z   File "/iloop-to-model/iloop_to_model/app.py", line 20, in wrapper
[web-1]2016-12-23T10:16:41.572075012Z     return await f(request, iloop)
[web-1]2016-12-23T10:16:41.572082867Z   File "/iloop-to-model/iloop_to_model/app.py", line 75, in sample_model
[web-1]2016-12-23T10:16:41.572091624Z     return await sample_in_phases(request, iloop, lambda x, y: model_for_phase(x, y, with_fluxes=with_fluxes, method=method))
[web-1]2016-12-23T10:16:41.572100231Z   File "/iloop-to-model/iloop_to_model/app.py", line 62, in sample_in_phases
[web-1]2016-12-23T10:16:41.572108154Z     return web.json_response(await for_phase(sample))
[web-1]2016-12-23T10:16:41.572115904Z   File "/iloop-to-model/iloop_to_model/app.py", line 56, in for_phase
[web-1]2016-12-23T10:16:41.572123732Z     return await function_for_phase(s, scalars[int(request.GET['phase-id'])])
[web-1]2016-12-23T10:16:41.572131824Z   File "/iloop-to-model/iloop_to_model/iloop_to_model.py", line 262, in model_for_phase
[web-1]2016-12-23T10:16:41.572140436Z     return await model_json(sample_model_id(sample), message_for_adjust(sample, scalars), with_fluxes=with_fluxes, method=method)
[web-1]2016-12-23T10:16:41.572148827Z   File "/iloop-to-model/iloop_to_model/iloop_to_model.py", line 258, in model_json
[web-1]2016-12-23T10:16:41.572157244Z     return await _call_with_return(model_id, adjust_message, return_message)
[web-1]2016-12-23T10:16:41.572270336Z   File "/iloop-to-model/iloop_to_model/iloop_to_model.py", line 151, in _call_with_return
[web-1]2016-12-23T10:16:41.572285569Z     call_result = await make_request(model_id, message)
[web-1]2016-12-23T10:16:41.572294477Z   File "/iloop-to-model/iloop_to_model/iloop_to_model.py", line 137, in make_request
[web-1]2016-12-23T10:16:41.572302642Z     return await r.json()
[web-1]2016-12-23T10:16:41.572309894Z   File "/usr/local/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 756, in json
[web-1]2016-12-23T10:16:41.572317597Z     return loads(stripped.decode(encoding))
[web-1]2016-12-23T10:16:41.572325069Z   File "/usr/local/lib/python3.5/json/__init__.py", line 319, in loads
[web-1]2016-12-23T10:16:41.572333148Z     return _default_decoder.decode(s)
[web-1]2016-12-23T10:16:41.572340308Z   File "/usr/local/lib/python3.5/json/decoder.py", line 339, in decode
[web-1]2016-12-23T10:16:41.572348634Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[web-1]2016-12-23T10:16:41.572355729Z   File "/usr/local/lib/python3.5/json/decoder.py", line 357, in raw_decode
[web-1]2016-12-23T10:16:41.572363293Z     raise JSONDecodeError("Expecting value", s, err.value) from None
[web-1]2016-12-23T10:16:41.572371046Z json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

which also brings up the point that we need some way to raise errors to the user somehow, now it just looks like everything worked even though the backend had an exception..

**Comment by hredestig** [comment]
This issue was moved to DD-DeCaF/model#2
